language: go

services:
  - mysql

go:
  - "1.8"
  - "1.9"
  - "1.10"
  - "tip"

before_install:
  - mysql -e 'CREATE DATABASE webapitest;'
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

script:
  - $GOPATH/bin/goveralls